<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>train_control_algorithm</name>
  <version>0.2.0</version>
  <description>Speed tracking node with PID state machine for train uncoupling robot</description>
  <maintainer email="1668657526@qq.com">zengxianwei</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>data_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
